import {client} from './client-config.mjs?v=15ecd476f284';
const nativeFetch=globalThis.fetch.bind(globalThis);
let consent=false,sdk=null;const rows=[],controllers=new Set(),gated=()=>navigator.globalPrivacyControl===true||navigator.doNotTrack==='1';
const view=()=>{document.querySelector('#result').textContent=JSON.stringify(rows,null,2);document.querySelector('#state').textContent=gated()?'PRIVACY SIGNAL — suppressed':consent?'ACCEPTED — explicit test only':'UNKNOWN / DECLINED — no vendor request';for(const id of ['sdk','direct'])document.getElementById(id).disabled=!consent||gated();};
const note=row=>{rows.push({at:new Date().toISOString(),...row});view();const completed=rows.findLast(r=>r.status>=100);document.querySelector("#latest").textContent=completed?completed.stage+" "+completed.status:row.stage;};
const props=version=>({schema_version:4,environment:'diagnostic',qa:true,probe_version:version,distinct_id:'synthetic-pass2431-healthcheck',$process_person_profile:false,$geoip_disable:true,$ip:null});
const nativeOpen=XMLHttpRequest.prototype.open,nativeSend=XMLHttpRequest.prototype.send;
XMLHttpRequest.prototype.open=function(method,url,...rest){this.__qaVendor=String(url).startsWith(client.apiHost+'/');return nativeOpen.call(this,method,url,...rest);};
XMLHttpRequest.prototype.send=function(body){if(this.__qaVendor){note({stage:'sdk_network_send',bodyBytes:typeof body==='string'?body.length:null});this.addEventListener('loadend',()=>note({stage:'sdk_network_result',status:this.status,accepted:this.status>=200&&this.status<300}));}return nativeSend.call(this,body);};
new PerformanceObserver(list=>{for(const e of list.getEntries())if(e.name.startsWith(client.apiHost+'/'))note({stage:'resource_finished',endpoint:new URL(e.name).pathname,status:e.responseStatus||null,ms:Math.round(e.duration)});}).observe({type:'resource',buffered:true});
document.addEventListener('securitypolicyviolation',e=>note({stage:'csp_violation',directive:e.violatedDirective}));
document.querySelector('#allow').onclick=()=>{consent=!gated();note({stage:'consent',allowed:consent,gpc:navigator.globalPrivacyControl===true,dnt:navigator.doNotTrack==='1'});};
document.querySelector('#decline').onclick=()=>{consent=false;for(const c of controllers)c.abort();sdk?.opt_out_capturing();note({stage:'withdrawn'});};
document.querySelector('#sdk').onclick=async()=>{if(!consent||gated())return;try{if(!sdk){note({stage:'sdk_load_start'});const {default:posthog}=await import('./posthog-sdk-1.438.3.mjs?v=b12c0a5b1ed5');if(!consent||gated())return;sdk=posthog.init(client.token,{api_host:client.apiHost,ui_host:'https://us.posthog.com',autocapture:false,capture_pageview:false,capture_pageleave:false,disable_session_recording:true,disable_surveys:true,disable_conversations:true,disable_product_tours:true,disable_external_dependency_loading:true,advanced_disable_flags:true,capture_dead_clicks:false,capture_exceptions:false,capture_performance:false,capture_heatmaps:false,enable_recording_console_log:false,rageclick:false,person_profiles:'never',persistence:'memory',disable_persistence:true,save_referrer:false,save_campaign_params:false,respect_dnt:true,ip:false,opt_out_capturing_by_default:true,opt_out_persistence_by_default:true,request_batching:false,disable_compression:true,api_transport:'XHR',before_send:e=>{note({stage:'sdk_defaults_keys',keys:Object.keys(e.properties).sort()});if(!consent||gated()||e.event!=='analytics_healthcheck')return null;e.properties={...props('24.3.1-https-sdk-v1'),token:client.token};return e;},loaded:()=>note({stage:'sdk_initialized',project:client.projectId}),on_request_error:()=>note({stage:'sdk_request_error'})});sdk.opt_in_capturing({captureEventName:false});}
 if(!consent||gated())return;note({stage:'sdk_capture_called'});sdk.capture('analytics_healthcheck',props('24.3.1-sdk-v1'),{send_instantly:true});}catch(e){note({stage:'sdk_error',name:e.name,message:e.message.slice(0,160)});}};
document.querySelector('#direct').onclick=async()=>{if(!consent||gated())return;const c=new AbortController();controllers.add(c);try{note({stage:'direct_capture_called'});const r=await nativeFetch(client.apiHost+'/i/v0/e/',{method:'POST',mode:'cors',credentials:'omit',referrerPolicy:'no-referrer',headers:{'Content-Type':'application/json'},body:JSON.stringify({api_key:client.token,event:'analytics_healthcheck',properties:props('24.3.1-https-direct-v1')}),signal:c.signal});note({stage:'direct_network_result',status:r.status,accepted:r.ok,response:(await r.text()).slice(0,100)});}catch(e){note({stage:'direct_error',name:e.name});}finally{controllers.delete(c);}};
view();
