import{client}from'../client-config.mjs?v=15ecd476f284';import{PrivacyState}from'./privacy-state.mjs?v=2257ac6b2ab7';import{Events,pageContext,context}from'./events.mjs?v=5ffbeca47f5e';import{PostHogAdapter as Failed}from'./failed-adapter.mjs?v=de2c3cc18c57';import{PostHogAdapter as Fixed}from'./fixed-adapter.mjs?v=c8b4aab5a6e1';
const rows=[],store=()=>{const m=new Map();return{getItem:k=>m.get(k)||null,setItem:(k,v)=>m.set(k,v),removeItem:k=>m.delete(k)}};let events,transport;
const signals=()=>({gpc:navigator.globalPrivacyControl===true,dnt:navigator.doNotTrack==='1'}),privacy=new PrivacyState({storage:store(),session:store(),signals});
const note=x=>{rows.push({at:new Date().toISOString(),...x});document.querySelector('#result').textContent=JSON.stringify(rows,null,2);};
const update=()=>{document.querySelector('#state').textContent=privacy.state;for(const id of ['fixed','failed'])document.getElementById(id).disabled=!privacy.allowed();};
new PerformanceObserver(l=>{for(const e of l.getEntries())if(e.name.startsWith(client.apiHost+'/'))note({stage:'native_network_finished',endpoint:new URL(e.name).pathname,status:e.responseStatus||null,ms:Math.round(e.duration)});}).observe({type:'resource',buffered:true});
document.querySelector('#allow').onclick=()=>{privacy.choose('ACCEPTED');privacy.setQA(true);note({stage:'consent',state:privacy.state,...signals()});update();};
document.querySelector('#deny').onclick=()=>{privacy.choose('WITHDRAWN');events?.synchronize();transport?.reset();note({stage:'withdrawn',state:privacy.state});update();};
async function run(name,Adapter){if(!privacy.allowed())return;transport=new Adapter({config:{enabled:true,approved:true,retentionApproved:true,projectToken:client.token,region:'us',privacySummary:'Explicit owner test consent for the existing PostHog production project.',allowedOrigins:[location.origin],vendorQA:true,coarseGeoVerified:false},origin:location.origin});events=new Events({privacy,transport});const emitted=events.emit('page_view','home',{...pageContext({page:'home'}),...context(),source:'exposure'});note({stage:'capture',adapter:name,emitted,queue:events.queue.length,tag:events.queue[0]?.traffic});const sent=await events.flush();note({stage:'flush_result',adapter:name,sent,remaining:events.queue.length});}
document.querySelector('#failed').onclick=()=>run('failed',Failed);document.querySelector('#fixed').onclick=()=>run('fixed',Fixed);update();
